input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "ambiente" => "aula"
      "stack" => "portflow"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "portflow-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}