spring:
  application:
    name: container-service
  datasource:
    url: jdbc:postgresql://localhost:5432/portflow?currentSchema=container_service
    username: portflow
    password: portflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          default_schema: container_service
          format_sql: true
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: portflow
      deployment.environment: local
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          protocol: http/protobuf
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 9080

api:
  endpoints:
    terminal: TERMINAL-SERVICE
