spring:
  profiles:
    active: prod
  application:
    name: terminal-service
  eureka:
    client:
      enabled: false


management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: portflow
      deployment.environment: local
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          protocol: http/protobuf
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus