spring:
  profiles:
    active: prod
  application:
    name: terminal-service
  eureka:
    client:
      enabled: false


management:
  endpoints:
    web:
      exposure:
        include: health,info